FROM python:3.10

COPY . .

ENV SECRET_KEY=LIASUDBFO87F8QWEOF8D
ENV FLASK_ENV=development
ENV DB_DIALECT=postgresql
ENV DB_DRIVER=psycopg2
ENV DB_NAME=tmp007
ENV DB_USER=tmp007
ENV DB_PASSWORD=tmp007
ENV DB_HOST=2.59.40.77
ENV DB_PORT=5432
ENV SQLALCHEMY_TRACK_MODIFICATIONS=True

RUN pip install -r requirements.txt

ENTRYPOINT ["python"]
CMD ["run.py"]
