apiVersion: apps/v1
kind: Deployment
metadata:
  name: copium-deployment
  labels:
     app: copium
     type: back-end
spec:
  template:
     metadata:
       name: copium-pod
       labels:
         app: copium
         type: back-end
     spec:
         containers:
           - name: copium
             image: "evkolotushin/test_jenkins:latest"
  replicas: 1
  selector:
    matchLabels:
      type: back-end

---
apiVersion: v1
kind: Service
metadata:
  name: copium-service
spec:
  selector:
    app: copium
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 80
      nodePort: 30000