apiVersion: apps/v1
kind: Deployment
metadata:
  name: copium-deployment
  labels:
     app: copium
     type: back-end
spec:
  template:
     metadata:
       name: copium-pod
       labels:
         app: copium
         type: back-end
     spec:
         containers:
           - name: copium
             image: "evkolotushin/test_jenkins:latest"
             envFrom:
               - configMapRef:
                   name: copium-configmap
               - secretRef:
                   name: db-secret
  replicas: 1
  selector:
    matchLabels:
      type: back-end

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
     app: react
     type: front-end
spec:
  template:
     metadata:
       name: react-pod
       labels:
         app: react
         type: front-end
     spec:
         containers:
           - name: react
             image: "evkolotushin/test_react:latest"
  replicas: 1
  selector:
    matchLabels:
      type: front-end

---
apiVersion: v1
kind: Service
metadata:
  name: copium-service
spec:
  selector:
    app: copium
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: copium-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "dev.websupplies.ru"
    http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: copium-service
            port:
              number: 5000
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: react-service
            port:
              number: 80
